# Generated by Django 2.2.7 on 2019-11-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=45)),
                ('contact_no', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'EmpDetails',
            },
        ),
    ]
