# Generated by Django 2.2.7 on 2019-11-12 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empmanagementapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empdetails',
            old_name='code',
            new_name='codeNo',
        ),
        migrations.RenameField(
            model_name='empdetails',
            old_name='contact_no',
            new_name='contactNo',
        ),
        migrations.RenameField(
            model_name='empdetails',
            old_name='email',
            new_name='emailId',
        ),
    ]
