# Generated by Django 2.2.7 on 2019-11-13 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empmanagementapp', '0002_auto_20191112_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empdetails',
            old_name='codeNo',
            new_name='code_no',
        ),
        migrations.RenameField(
            model_name='empdetails',
            old_name='contactNo',
            new_name='contact_no',
        ),
        migrations.RenameField(
            model_name='empdetails',
            old_name='emailId',
            new_name='email_id',
        ),
    ]
