# Generated by Django 2.0.3 on 2019-11-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empmanagementapp', '0004_auto_20191114_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetails',
            name='code_no',
            field=models.IntegerField(max_length=5),
        ),
    ]
