# Generated by Django 2.0.3 on 2019-11-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empmanagementapp', '0005_auto_20191114_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetails',
            name='code_no',
            field=models.IntegerField(),
        ),
    ]
